baseURL = '/'
languageCode = 'en-us'
title = 'Sun Sea Sangria'
theme = 'paige'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Welcome to Sun Sea Sangria"

[params.paige.site]
  disable_breadcrumbs = true
  disable_credit = true
