[build]
  publish = "public"
  command = "export DART_SASS_VERSION=1.94.2 && curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && tar -xvf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && export PATH=$PATH:$PWD/dart-sass && hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.152.2"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "export DART_SASS_VERSION=1.94.2 && curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && tar -xvf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && export PATH=$PATH:$PWD/dart-sass && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "export DART_SASS_VERSION=1.94.2 && curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && tar -xvf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz && export PATH=$PATH:$PWD/dart-sass && hugo --gc --minify -b $DEPLOY_PRIME_URL"
